In [2]:
# 试试三个类别的小数据
from mxnet.gluon import data as gdata
import os

data_dir = '../../../food3'

imgs = gdata.vision.ImageFolderDataset(data_dir)

In [3]:
imgs

In [4]:
imgs.__len__()

3000

In [8]:
# img, label = 
imgs.__getitem__(2099) # 此函数返回 img, label，2099属于第三类，返回label为2
# 上面语句 == imgs[2099]

(
 [[[ 63  34  39]
   [ 64  35  40]
   [ 65  36  41]
   ...
   [101 102 120]
   [100 101 119]
   [ 98  99 117]]
 
  [[ 64  35  40]
   [ 65  36  41]
   [ 66  37  42]
   ...
   [100 101 119]
   [100 101 119]
   [ 97  98 116]]
 
  [[ 65  36  41]
   [ 66  37  42]
   [ 66  37  42]
   ...
   [100 101 119]
   [ 99 100 118]
   [ 97  98 116]]
 
  ...
 
  [[  4   5   9]
   [  4   5   9]
   [  4   5   9]
   ...
   [123 122 130]
   [125 124 130]
   [125 124 130]]
 
  [[  4   5   9]
   [  4   5   9]
   [  4   5   9]
   ...
   [122 121 127]
   [124 123 129]
   [124 123 129]]
 
  [[  4   5   9]
   [  4   5   9]
   [  4   5   9]
   ...
   [122 121 127]
   [124 123 129]
   [124 123 129]]]
 <NDArray 342x512x3 @cpu(0)>, 2)

In [22]:
# 指定RGB三个通道的均值和方差来将图像通道归一化
normalize = gdata.vision.transforms.Normalize(
    [0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

augs = gdata.vision.transforms.Compose([
    gdata.vision.transforms.RandomResizedCrop(224),
    gdata.vision.transforms.RandomFlipLeftRight(),
    gdata.vision.transforms.ToTensor(),
    normalize])

iter = gdata.DataLoader(imgs.transform_first(augs), batch_size=100, shuffle=True)

In [23]:
iter

In [27]:
iter.__len__()

30

In [40]:
train = []
test = []
sep = int(0.7*iter.__len__())
for i, batch in enumerate(iter):
    if(i<sep):
        train += batch
    else:
        test += batch

In [37]:
batch # batch是两个NDArray

[
 [[[[-0.11430778 -0.49105233 -0.43967807 ... -1.5356624  -1.4157891
     -1.4329139 ]
    [-0.11430778 -0.49105233 -0.59380084 ... -1.5356624  -1.3986644
     -1.1760426 ]
    [-0.13143253 -0.5081771  -0.7479236  ... -1.6897851  -1.5699118
     -1.3815396 ]
    ...
    [ 0.7761795   0.7761795   0.7761795  ... -1.8952821  -1.8781574
     -1.8781574 ]
    [ 0.86180323  0.8446785   0.86180323 ... -1.8267832  -1.8267832
     -1.9124069 ]
    [ 0.93030226  0.9131775   0.9131775  ... -1.843908   -1.8610327
     -1.9980307 ]]
 
   [[-0.740196   -1.0903361  -1.0028011  ... -1.8081232  -1.7030813
     -1.5805322 ]
    [-0.670168   -0.9852941  -0.9852941  ... -1.7906162  -1.6505601
     -1.30042   ]
    [-0.565126   -0.862745   -0.9677871  ... -1.9306722  -1.8081232
     -1.5280112 ]
    ...
    [ 1.8683473   1.8508403   1.8508403  ... -1.6330532  -1.6155462
     -1.6155462 ]
    [ 1.9383754   1.9033613   1.9208683  ... -1.5630252  -1.5630252
     -1.6505601 ]
    [ 1.9733893   1.9383754   1.9

In [41]:
train

[
 [[[[ 0.3651854   0.38231018  0.3651854  ... -1.6726604  -1.6726604
     -1.7240347 ]
    [ 0.00556549  0.12543888  0.17681314 ... -1.5870366  -1.5870366
     -1.6384109 ]
    [-0.45680285 -0.4739276  -0.38830382 ... -1.6384109  -1.6384109
     -1.7411594 ]
    ...
    [ 0.34806067  0.33093593  0.31381115 ...  0.39943492  0.46793392
      0.46793392]
    [ 0.33093593  0.31381115  0.27956167 ...  0.45080918  0.45080918
      0.45080918]
    [ 0.38231018  0.38231018  0.3651854  ...  0.43368444  0.43368444
      0.45080918]]
 
   [[ 0.90546227  0.90546227  0.81792724 ...  0.3627452   0.3277312
      0.2752102 ]
    [ 0.6778712   0.74789923  0.76540625 ...  0.41526622  0.41526622
      0.3627452 ]
    [ 0.2752102   0.2051822   0.2577032  ...  0.3452382   0.3627452
      0.2752102 ]
    ...
    [ 0.41526622  0.45028022  0.4677872  ...  0.57282925  0.64285725
      0.62535024]
    [ 0.41526622  0.45028022  0.45028022 ...  0.6078432   0.62535024
      0.62535024]
    [ 0.48529422  0.5203082

ndarray保存为文件，可以在后面追加吗？

In [2]:
from mxnet import nd

In [8]:
x = nd.ones(4)
y = nd.zeros(4)
nd.save('xy', [x, y])
mix = nd.load('xy')
mix

[
 [1. 1. 1. 1.]
 <NDArray 4 @cpu(0)>, 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>]

In [9]:
z = nd.ones(5)
nd.save('xy',z)
mix3 = nd.load('xy')
mix3  # 不能追加？？

[
 [1. 1. 1. 1. 1.]
 <NDArray 5 @cpu(0)>]